import "server-only";
import fs from "node:fs";
import path from "node:path";

export interface BuildInfo {
  commit: string;
  commit_subject: string;
  built_at: string;
  recent_commits: { sha: string; subject: string }[];
}

let cached: BuildInfo | null = null;

const FALLBACK: BuildInfo = {
  commit: "unknown",
  commit_subject: "(build-info.json missing)",
  built_at: new Date(0).toISOString(),
  recent_commits: [],
};

/**
 * Reads apps/web/build-info.json (generated by scripts/write-build-info.mjs
 * during `pnpm build`). Cached in-process; no shell-outs at runtime.
 */
export function getBuildInfo(): BuildInfo {
  if (cached) return cached;
  try {
    // The file lives next to this module's "apps/web" root. In dev mode we
    // run from that dir; in prod (next start) we also run from that dir.
    const filePath = path.resolve(process.cwd(), "build-info.json");
    const text = fs.readFileSync(filePath, "utf8");
    const parsed = JSON.parse(text) as Partial<BuildInfo>;
    cached = {
      commit: typeof parsed.commit === "string" ? parsed.commit : FALLBACK.commit,
      commit_subject:
        typeof parsed.commit_subject === "string"
          ? parsed.commit_subject
          : FALLBACK.commit_subject,
      built_at:
        typeof parsed.built_at === "string" ? parsed.built_at : FALLBACK.built_at,
      recent_commits: Array.isArray(parsed.recent_commits)
        ? parsed.recent_commits
            .filter(
              (c): c is { sha: string; subject: string } =>
                typeof c === "object" &&
                c !== null &&
                typeof (c as { sha?: unknown }).sha === "string" &&
                typeof (c as { subject?: unknown }).subject === "string",
            )
            .slice(0, 5)
        : [],
    };
  } catch {
    cached = FALLBACK;
  }
  return cached;
}
